services:
  booking-agent-db:
    image: postgres:18-alpine
    container_name: booking_agent_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data_agent:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

  crawler-agent:
    image: crawler-agent:${APP_VERSION:-latest}
    container_name: crawler-agent-container
    depends_on:
      - booking-agent-db
    environment:
      DB_TYPE: postgresql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TWO_CAPTCHA_API_KEY: ${TWO_CAPTCHA_API_KEY}
      PYTHONUNBUFFERED: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    build:
      context: ./crawler
      dockerfile: Dockerfile

  frontend:
    image: frontend:${APP_VERSION:-latest}
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://localhost:8000}
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://localhost:8000}
    restart: unless-stopped

volumes:
  pg_data_agent:
