CREATE TABLE TB_BOOKING_THICKET (
    BOOKING_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(10) NOT NULL,
    ADULT_COUNT INT,
    CHILD_COUNT INT,
    STUDENT_COUNT INT,
    ELDER_COUNT INT,
    DISABLED_COUNT INT,
    TICKET_TYPE VARCHAR(20) NOT NULL,
    TICKET_NUMBER VARCHAR(20) NOT NULL,
    BOOKING_DATE DATE NOT NULL,
    BOOKING_TIME TIME NOT NULL,
    START_STATION VARCHAR(50) NOT NULL,
    END_STATION VARCHAR(50) NOT NULL,
    IS_EARLY_BIRD BOOLEAN DEFAULT FALSE,
    CAN_BOOK_DATE DATE NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);