CREATE TABLE TB_EARLY_BIRD (
    EARLY_BIRD_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BOOKING_ID BIGINT NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (BOOKING_ID) REFERENCES TB_BOOKING_THICKET(BOOKING_ID)
);