CREATE TABLE TB_EARLY_BIRD (
    EARLY_BIRD_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOOKING_ID BIGINT NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    CREATED_TIME TIMESTAMPTZ,
    UPDATED_TIME TIMESTAMPTZ,
    FOREIGN KEY (BOOKING_ID) REFERENCES TB_BOOKING_TICKET(BOOKING_ID)
);