CREATE TABLE TB_SYS_PARM(
    PARM_ID INT NOT NULL PRIMARY KEY,
    PARM_CATEGORY VARCHAR(50) NOT NULL,
    PARM_NAME VARCHAR(50) NOT NULL,
    PARM_VALUE VARCHAR(255) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP TIMEZONE 'Asia/Taipei',
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP TIMEZONE 'Asia/Taipei' ON UPDATE CURRENT_TIMESTAMP TIMEZONE 'Asia/Taipei'
);